version: '3.9'

services:
  portfolio:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./Portfolio:/Portfolio
      - ./static:/static
    command: python manage.py runserver 0.0.0.0:8000
