# Generated by Django 4.2.1 on 2024-04-14 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Pojištění',
                'verbose_name_plural': 'Pojištění',
            },
        ),
        migrations.CreateModel(
            name='Insured',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=25)),
            ],
            options={
                'verbose_name': 'Pojištěné osoby',
                'verbose_name_plural': 'Pojištěné osoby',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Statistiky',
                'verbose_name_plural': 'Statistiky',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uživatelské role',
                'verbose_name_plural': 'Uživatelské role',
            },
        ),
        migrations.CreateModel(
            name='InsuranceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('description', models.TextField()),
                ('insurance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.insurance')),
            ],
            options={
                'verbose_name': 'Pojistné události',
                'verbose_name_plural': 'Pojistné události',
            },
        ),
        migrations.AddField(
            model_name='insurance',
            name='insured_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pojisteni.insured'),
        ),
    ]
